name: yandex_mapkit_web
description: A Flutter plugin for integrating Yandex.MapKit in Web applications.
version: 1.0.0
homepage: https://github.com/Vasew/yandex_mapkit_web

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.vasew.yandexmapkitweb
        pluginClass: YandexMapkitWebPlugin
      ios:
        pluginClass: YandexMapkitWebPlugin
